### ISSUE TITLE
Missing "Robotics" menu in the editor

### ISSUE THREAD

**Issue by m-talha** [Unity-Technologies/Unity-Robotics-Hub#153]
Hi,

I seem to be missing the "Robotics" menu in the Unity editor. Instead my menu looks like this:

![image](https://user-images.githubusercontent.com/15839351/108129193-be53a680-70a5-11eb-8398-f185f1f881bd.png)

Following the tutorial for pick and place, I need the menu for the ROS settings. Is the tutorial outdated or is there something wrong with my installation?

Thanks

**Comment by hyounesy** [comment]
Hi @m-talha, we just recently updated our ROS-TCP-Packages and the tutorial. So you may be using an older version of the project with the newer documentation. Could you please try getting the most recent version of the Pick and Place project?

**Comment by m-talha** [comment]
Updating the package solved it thanks.
