### ISSUE TITLE
MoveIT Solver is not aware of robot unity position?

### ISSUE THREAD

**Issue by mrceresa** [Unity-Technologies/Unity-Robotics-Hub#173]
Dear all,
thanks for the great examples and apologies if I ask a silly question. 

If I move the robot arm in unity, how can I make the solver aware that its position changed? It happily continues to plan a trajectory even if the targets are now out of reach
![uros_plan](https://user-images.githubusercontent.com/524047/109631899-bafcf800-7b46-11eb-9303-5dd140696283.jpg)

Thanks and regards,

Mario

**Comment by LaurieCheers-unity** [comment]
Hi there; yes, this demo makes the assumption that the robot has not been moved in Unity.

If you'd like the robot to be at a different fixed position you can tell MoveIt about it by adjusting its position in the URDF file (https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/main/tutorials/pick_and_place/ROS/src/niryo_one_urdf/niryo_one.urdf.xacro#L171).

If you need a dynamic solution, try subtracting the robot's position from the positions reported in TrajectoryPlanner. PublishJoints.

**Comment by mpinol** [comment]
Looks like the question was answered. Please don't hesitate to reach out if you have any other questions!
