### ISSUE TITLE
Can the DockerFile be shared

### ISSUE THREAD

**Issue by NathanielRose** [Unity-Technologies/Unity-Robotics-Hub#190]
In the tutorials theres a docker image that is used as an alternative for the pickandplace example.
Can the DockerFile used for the image: `unity-robotics:pick-and-place` be shared. Attempting to get this to work on WSL has become quite a hassle.

**Comment by peifeng-unity** [comment]
Hello @NathanielRose, the DockerFile is located in tutorials/pick_and_place/docker/Dockerfile of the repository and you can use [this link](https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/main/tutorials/pick_and_place/docker/Dockerfile) to find it. Please let us know if it helps.

**Comment by NathanielRose** [comment]
Thank you, for some reason this wasnt showing in the search results.
