### ISSUE TITLE
Every Service message create new TCP connection

### ISSUE THREAD

**Issue by dasannikov** [Unity-Technologies/Unity-Robotics-Hub#197]
Every service message create new TCP connection. Looks like waste of resources and slower service response time.

![Снимок экрана 2021-04-09 130841](https://user-images.githubusercontent.com/1015770/114171885-36677b80-9935-11eb-99dc-9362121746e1.png)

**Comment by hyounesy** [comment]
Hi @dasannikov, thanks for bringing this to our attention. I added a ticket to address this.

**Comment by LaurieCheers-unity** [comment]
Hi, this is fixed in the new release (v.0.4.0).
