### ISSUE TITLE
No Message published after Starting server on 192.168.178.58:10000 ROS-Unity Handshake received, will connect to 192.168.178.54:5005 when publish button pushed

### ISSUE THREAD

**Issue by florianspy** [Unity-Technologies/Unity-Robotics-Hub#224]
**Describe the bug**
Following the pick-and-place tutorial till the step roslaunch niryo_moveit part_2.launch
Instead of  geting the heard message in terminal i only get the ROS-Unity Handshake received and but then nothing when the publish button is pushed
This happens with the docker image and ros melodic running in a VM

**Comment by hyounesy** [comment]
Thanks for reporting the issue. We will investigate ASAP and get back to you.
Internal ticket #  AIRO-687

**Comment by hyounesy** [comment]
Hi @florianspy, Would you please check the following:

- do you see any error message on the Console on the UnityEditor after pressing play?
- on the info box top left corner of the Game panel in the window, toggle the [View Service Status] checkbox. Do you see "handshake Service Requested" and "handshake Service Response"?
- With the "Publisher" GameObject selected in the Hierarchy pane, check that the properties for "Source Destination Publisher" in the Inspector pane are all set.

**Comment by florianspy** [comment]
@hyounesy 
1. No Errors in the console
![noerrorconsole](https://user-images.githubusercontent.com/39183098/119451701-dd617480-bd35-11eb-95ba-b910d9abcac0.png)
2. Handshake service response is there 
![handshakeserviceresponse](https://user-images.githubusercontent.com/39183098/119451806-f538f880-bd35-11eb-9021-08f645ecc491.png)
3. Publisher object setup as explained in tutorial
![sourcedestinationpublisher](https://user-images.githubusercontent.com/39183098/119451817-f9651600-bd35-11eb-84ec-fba50df29659.png)

**Comment by hyounesy** [comment]
Thanks for the info @florianspy , Based on your 2nd screenshot, looks like the UNITY IP may not be setup. Please try the following:
- In Unity Editor click on the main menu item: Robotics -> ROS Settings
- set the "Override Unity IP Address" field to the local IP of the machine running the Unity Editor. 
- close the "ROS Setting" window
- In Unity Editor click on the main menu item: File -> Save Project

**Comment by florianspy** [comment]
@hyounesy 
I adopted the settings 
![image](https://user-images.githubusercontent.com/39183098/119621623-a14a1480-be06-11eb-934d-9a3c97ea9507.png)
unfortunately still no information on ros side
![image](https://user-images.githubusercontent.com/39183098/119621832-deaea200-be06-11eb-962c-bc9cb36c12e3.png)

**Comment by hyounesy** [comment]
Hi @florianspy , Based on the screenshot above, look like the ROS IP address is incorrectly set to the local Unity IP address. Please try changing it to 127.0.0.1 in the ROS Settings in your Unity Editor.

**Comment by florianspy** [comment]
Dear @hyounesy  with this setting i instantly get the following error message:
![image](https://user-images.githubusercontent.com/39183098/120167605-3af63500-c1fe-11eb-8f6a-fc41151ae832.png)
Note that my ros runs in a vm.

**Comment by florianspy** [comment]
Dear @hyounesy  I figured now out where there problem is with a friend of mine. So basically the EventSystem was missing that why buttons never worked, so it has nothing to due with the ip. So please add to the instruction to add the EventSystem.

**Comment by hyounesy** [comment]
Hi @florianspy , Thanks for letting us know. I am happy that you managed to resolve the issue. It is strange that you didn't have the EventSystem object as it is automatically added to the scene as soon as a UI object like a button is added to the scene. Was it possibly deleted by mistake? We will update the troubleshooting document as you suggested.
Not having the EventSystem can in fact be reason for the  UI events not to trigger. However it would not cause the "Socket Exception: Connection Refused" issue you mentioned above. Are you still experiencing the connection issue?

**Comment by hyounesy** [comment]
internal ticket#: AIRO-749

**Comment by florianspy** [comment]
The only additional thing I did which is probably not necessary as you don't communicate via Ros port 11311 but via 10000 is in bashrc file the variable link ROS_HOSTNAME and Ros_master_uri to the IP address of ros. 
"The socket refused to connect" only happened when i gave in Unity localhost as the adresse of ROS and not the ip of the system running ROS which makes sense as ROS was running in the VM and not directly on localhost

**Comment by sdiao** [comment]
Hi @florianspy, thanks for the update. We just released several ROSConnection improvements in [ROS-TCP-Connector v0.4.0 ](https://github.com/Unity-Technologies/ROS-TCP-Connector/tree/v0.4.0). We have simplified the ROS Setting window in Unity Editor. I would recommend check out the latest features with the pick and place tutorial. Please let us know if there is anything else we can help with. Thank you.

**Comment by florianspy** [comment]
Dear @sdiao  I upgraded to the newest version it works. 
However before I could get it working i had to change the Demo.cs file to the latest release avoid errors with rosConnection missing. 
Then i had to download the latest version of the ROSpackage otherwise i got the error "Can't send a message, no defined unity IP!".
Additionally Topic Name of the SourceDestinationPublisher currently seems to be not used anymore, because  even if i give "SourceDestination_input" in unity still "SourceDestination" is used.
![image](https://user-images.githubusercontent.com/39183098/120443750-3e68f800-c387-11eb-8024-09877d55b305.png)
![image](https://user-images.githubusercontent.com/39183098/120443826-50e33180-c387-11eb-8efa-41421cbaa4a4.png)

**Comment by sdiao** [comment]
Hi @florianspy , I am glad the v0.4.0 works for you. Yes, we would recommend upgrade to v0.4.0 in Unity Robotics Hub and ROS-TCP-Endpoint as well. For the topic name, the TopicName in SourceDestinationPublisher is used. The confusion is because in ROS, we registered the topic as below in [server_endpoint](https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/v0.4.0/tutorials/pick_and_place/ROS/src/niryo_moveit/scripts/server_endpoint.py#L18):
`'SourceDestination_input': RosPublisher('SourceDestination', NiryoMoveitJoints, queue_size=10)`

Hence, `rostopic list` returns `SourceDestination` while the validation is using `SourceDestination_input`.  Hope it helps. Let me know if you have further questions. Thanks.
