### ISSUE TITLE
Can't build a the project from Unity for Universal Windows Platform

### ISSUE THREAD

**Issue by SMRazaRizvi96** [Unity-Technologies/Unity-Robotics-Hub#254]
I created a Unity project and used the ROS-TCP-Connector package to communicate between Unity and ROS.

I followed the first three steps from here: https://github.com/Unity-Technologi...s-2/tutorials/ros_unity_integration/README.md

It works fine on Unity and messages are sent from Unity to ROS, but as soon as I build the project from Unity, to open it in Visual Studio, it gives me the following errors in Unity:

![upload_2021-7-12_15-14-59](https://user-images.githubusercontent.com/74411560/125295238-51c39780-e325-11eb-8ba6-4f140b07a0b6.png)
![upload_2021-7-12_15-15-19](https://user-images.githubusercontent.com/74411560/125295240-525c2e00-e325-11eb-94a0-eff61320fe5d.png)
![upload_2021-7-12_15-15-36](https://user-images.githubusercontent.com/74411560/125295243-52f4c480-e325-11eb-91ab-fbe77206751c.png)

These are the build settings I am using:

upload_2021-7-12_15-14-23.png
![upload_2021-7-12_15-14-23](https://user-images.githubusercontent.com/74411560/125295236-512b0100-e325-11eb-88a3-cd5031d8df10.png)

**Comment by hyounesy** [comment]
Hi, Thanks for bringing this to our attention. We will look into this error and get back to you with a potential solution.

Ticket#: AIRO-974

**Comment by SMRazaRizvi96** [comment]
I solved the issue.

Solution: By default, the Universal Windows Platform is not checked in the 'Unity.Robotics.ROSTCPConnector.asmdef' file inside the ROS-TCP Connector Package, and the file is locked and cannot be edited from Unity. So, I opened the file locally on my laptop on the Notepad and added the line "WSA" under the supported platforms (Can be seen in the image attached below).

After adding this line, I saved the file, recompiled the Unity project, AND THE BUILD WORKED!!

![Build-Issue](https://user-images.githubusercontent.com/74411560/125457382-88c76936-b0d9-486b-92c4-15281e4df2be.JPG)

**Comment by peifeng-unity** [comment]
Thanks, @SMRazaRizvi96! It is so great to know that you figured it out. It is good for us to learn and we will update the supporting platforms.

**Comment by sdiao** [comment]
Support for windows build is merged in https://github.com/Unity-Technologies/URDF-Importer/pull/124. Close this issue now.

**Comment by SMRazaRizvi96** [comment]
Thank you so much for the support and quick actions.
