### ISSUE TITLE
No respond on ROS terminal when testing TCP connection

### ISSUE THREAD

**Issue by kisstherain8677** [Unity-Technologies/Unity-Robotics-Hub#275]
Hello,thanks for you guys tutorials .I went through Pick-and-Place Tutorial: Part 2 and pressing publish button,there is nothing print on ROS terminal.

![image](https://user-images.githubusercontent.com/41934902/126924237-0b979660-353d-49af-a157-53604f4c0309.png)

I run ROS in docker,and I have checked the ROS IP:
![image](https://user-images.githubusercontent.com/41934902/126924298-3a1eb3a5-23f1-4bcc-8460-e7a0918ac0a5.png)

![image](https://user-images.githubusercontent.com/41934902/126924572-7c4ac73f-592c-4919-b9b2-f671c4d4083b.png)

warning in unity:

SendMessage cannot be called during Awake, CheckConsistency, or OnValidate
UnityEngine.GameObject:AddComponent<Unity.Robotics.ROSTCPConnector.HUDPanel> ()
Unity.Robotics.ROSTCPConnector.ROSConnection:InitializeHUD () (at Library/PackageCache/com.unity.robotics.ros-tcp-connector@f7f669f212/Runtime/TcpConnector/ROSConnection.cs:371)
Unity.Robotics.ROSTCPConnector.ROSConnection:OnValidate () (at Library/PackageCache/com.unity.robotics.ros-tcp-connector@f7f669f212/Runtime/TcpConnector/ROSConnection.cs:361)
UnityEngine.Resources:Load<UnityEngine.GameObject> (string)

**Environment**
- Unity Version: [Unity 2020.3.13f1]
- Unity machine OS: Windows 10
- ROS machine OS : [Windows10 on Docker, ROS melodic]
- ROS–Unity communication: [Docker]

**Comment by sdiao** [comment]
Hi @kisstherain8677 , thanks for reaching out. The warning that you posted is harmless if you are running from the Unity Editor. Was there any error or info from your Unity Editor's console output? Were you able to run the Pick and Place Quick Demo https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/main/tutorials/pick_and_place/quick_demo.md before doing the Part 2 tutorial? I would recommend to start with the Quick Demo if you haven't done so. 
Based on the screenshot you shared, the connection between Unity and ROS is good.

**Comment by kisstherain8677** [comment]
Thacks for your reply! I did run the quick_demo,but the robot didn't move either. I guess it should have moved while function publisher.PublishJoints() executes in update()?

no error info print in unity consule or ROS terminal

here are my screen shots
**unity**
![image](https://user-images.githubusercontent.com/41934902/127096287-efece367-b631-4ac3-ba7b-e1673a613931.png)

![image](https://user-images.githubusercontent.com/41934902/127096340-1cb41377-38b6-418c-9feb-d41b114370f5.png)

**ROS terminal**
![image](https://user-images.githubusercontent.com/41934902/127096474-24994d6d-382a-4229-bd30-a8d92570e841.png)

**Comment by kisstherain8677** [comment]
Hi! I checked the port 127.0.0.1:10000 and found that a service occupied this port...it's ok after I killing it ,sorry for taking your time and thank you!

**Comment by sdiao** [comment]
No worries. I am glad you figured it out. Feel free to reach out if you have further questions.
