### ISSUE TITLE
Pick and place doesn't work because Ubuntu(ROS) doesn't return a response.

### ISSUE THREAD

**Issue by KazukiKuriyama** [Unity-Technologies/Unity-Robotics-Hub#278]
**Describe the bug**
I tried "Pick-and-Place Demo Part 3: Pick-and-Place In Unity", but at the time of release, the trajectory was displayed on the console side of Docker, but no response was returned to Unity side.
Of course, the response callback doesn't work.

I also used WireShark to monitor packets on the cable between my Windows 10 PC and Ubuntu 18.04, but it seems that only ACK was returned from the Ubuntu side.

Is it possible to run the demo in my environment?

**To Reproduce**
Execute "Pick-and-Place Demo Part 3: Pick-and-Place In Unity" in the following environment.

**Environment (please complete the following information, where applicable):**
- Unity Version: [e.g. Unity 2020.3.14f1]
- Unity machine OS + version: [ Windows 10]
  Firewall has been set to disabled
- ROS machine OS + version: [ Ubuntu 18.04, ROS melodic]
  Firewall has been set to disabled
- ROS–Unity communication: [Docker]
  Execute ROS from Docker as described in the pick-and-place demo procedure manual.
- Branch or version: [Remove ROS2 Beta Mentions (#272)]
- The two PCs are directly connected by a LAN cable.
![image](https://user-images.githubusercontent.com/64897247/127587055-6062a69d-d318-4324-8506-c6455c29a290.png)

**Additional context**
When I install Unity on an Ubuntu PC, the response comes back without any problems and the robot works correctly, but I want to receive the response from windows 10.

Docker command line at runtime
> [INFO] [1627605135.436332]: Connection from 192.168.0.3
> [ERROR] [1627605141.161601]: Topic '__request' is not registered! Known topics are: ['sim_real_pnp', 'SourceDestination_input', 'niryo_one/commander/robot_action/goal', 'niryo_moveit', 'NiryoTrajectory'] 
> [ INFO] [1627605141.181512343]: Loading robot model 'niryo_one'...
> [ INFO] [1627605141.181554357]: No root/virtual joint specified in SRDF. Assuming fixed joint
> [ INFO] [1627605142.308458867]: Ready to take commands for planning group arm.
> [ INFO] [1627605142.539769485]: Planning request received for MoveGroup action. Forwarding to planning pipeline.
> [ INFO] [1627605142.540888462]: Planner configuration 'arm' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
> [ INFO] [1627605142.541390132]: RRTConnect: Starting planning with 1 states already in datastructure
> [ INFO] [1627605142.552759402]: RRTConnect: Created 5 states (2 start + 3 goal)
> [ INFO] [1627605142.552789940]: Solution found in 0.011560 seconds
> [ INFO] [1627605142.559455599]: SimpleSetup: Path simplification took 0.006640 seconds and changed from 4 to 2 states
> [ INFO] [1627605142.598981173]: Planning request received for MoveGroup action. Forwarding to planning pipeline.
> [ INFO] [1627605142.599564907]: Planner configuration 'arm' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
> [ INFO] [1627605142.599794954]: RRTConnect: Starting planning with 1 states already in datastructure
> [ INFO] [1627605142.612106843]: RRTConnect: Created 5 states (2 start + 3 goal)
> [ INFO] [1627605142.612175655]: Solution found in 0.012460 seconds
> [ INFO] [1627605142.617479002]: SimpleSetup: Path simplification took 0.005252 seconds and changed from 4 to 2 states
> [ INFO] [1627605142.659363505]: Planning request received for MoveGroup action. Forwarding to planning pipeline.
> [ INFO] [1627605142.659941095]: Planner configuration 'arm' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
> [ INFO] [1627605142.660201384]: RRTConnect: Starting planning with 1 states already in datastructure
> [ INFO] [1627605142.672171567]: RRTConnect: Created 4 states (2 start + 2 goal)
> [ INFO] [1627605142.672233112]: Solution found in 0.012124 seconds
> [ INFO] [1627605142.679202564]: SimpleSetup: Path simplification took 0.006899 seconds and changed from 3 to 2 states
> [ INFO] [1627605142.719025637]: Planning request received for MoveGroup action. Forwarding to planning pipeline.
> [ INFO] [1627605142.719574847]: Planner configuration 'arm' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
> [ INFO] [1627605142.719803061]: RRTConnect: Starting planning with 1 states already in datastructure
> [ INFO] [1627605142.750997128]: RRTConnect: Created 5 states (2 start + 3 goal)
> [ INFO] [1627605142.751022022]: Solution found in 0.031300 seconds
> [ INFO] [1627605142.757745339]: SimpleSetup: Path simplification took 0.006699 seconds and changed from 4 to 2 states

**Comment by sdiao** [comment]
Hi @KazukiKuriyama , thanks for reaching out. Short answer is that you should be able to run the tutorial with Unity running on a Windows machine and ROS running on Ubuntu.  We are looking into the issue and will let you know once we have an update. Was there any error or warning on either ROS or Unity side?

**Comment by KazukiKuriyama** [comment]
Thank you for your support!

I don't know the relevance, but I get the following error on the Unity console:
> ArgumentException: JSON parse error: Invalid value.
UnityEngine.JsonUtility.FromJson (System.String json, System.Type type) (at <0b59f3b614a04547a8bf657de1e23f2c>:0)
UnityEngine.JsonUtility.FromJson[T] (System.String json) (at <0b59f3b614a04547a8bf657de1e23f2c>:0)
Unity.Robotics.ROSTCPConnector.ROSConnection.ReceiveSysCommand (System.String topic, System.String json) (at Library/PackageCache/com.unity.robotics.ros-tcp-connector@f7f669f212/Runtime/TcpConnector/ROSConnection.cs:433)
Unity.Robotics.ROSTCPConnector.ROSConnection.Update () (at Library/PackageCache/com.unity.robotics.ros-tcp-connector@f7f669f212/Runtime/TcpConnector/ROSConnection.cs:395)


The contents of Json at that time are as follows.

> "�\0\0\0Topic \'__request\' is not registered! Known topics are: [\'sim_real_pnp\', \'SourceDestination_input\', \'niryo_one/commander/robot_action/goal\', \'niryo_moveit\', \'NiryoTrajectory\'] "

**Comment by KazukiKuriyama** [comment]
I added a block diagram and a Docker console to the first comment.

**Comment by KazukiKuriyama** [comment]
I made a little progress.
Only on the Windows side where Unity is installed
After changing to v.0.4.0, I confirmed that the robot works without any problem.
When I cloned v.0.5.0 again in that environment, it didn't work in this version as before.


Isn't there a bug between v.0.4.0 and v.0.5.0?

There are other points I noticed.
-It did not occur in v.0.4.0, but in v.0.5.0, "RosMessageTypes.NiryoMoveit" is not recognized in the namespace unless the C # file permissions are changed.
-In v.0.5.0, "git submodule" is always required because the contents of "tutorials \ pick_and_place \ ROS \ src" are only slightly recognized by the ROS settings.

**Comment by sdiao** [comment]
Thanks for the detailed notes. It sounds like there might be a bug introduced between v0.4.0 and v0.5.0. We are investigating.

**Comment by sdiao** [comment]
The version of ROS-TCP-Connector has to be the same as ROS-TCP-Endpoint. Based on "After changing to v.0.4.0, I confirmed that the robot works without any problem", it seems that your ROS-TCP-Endpoint is on v0.4.0 in Docker, even though the Unity project switched to v0.5.0. 
Please use git submodule when you update the Unity-Robotics-Hub, and rebuild your docker container. 

You can check the version in Unity-Robotics-Hub/tutorials/pick_and_place/ROS/src/ros_tcp_endpoint/package.xml
Something like:
`<?xml version="1.0"?>
<package format="2">
  <name>ros_tcp_endpoint</name>
  <version>0.5.0</version>`

Please let us know if it helps. Thanks.

**Comment by KazukiKuriyama** [comment]
Thank you for your reply.
When I checked the xml file, "0.4.0" was displayed, so I think that was the cause.
When I tried it with "0.5.0" Docker, I was able to confirm that the communication was successful!
