### ISSUE TITLE
The Ross Setting screen of ROS – Unity Integration Networking is different from the current menu.

### ISSUE THREAD

**Issue by KazukiKuriyama** [Unity-Technologies/Unity-Robotics-Hub#279]
**Describe the bug**
The Ross Setting screen of ROS – Unity Integration Networking is different from the current menu.
Currently, there is no text box to set Unity's IP address. Is it unnecessary?

https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/main/tutorials/ros_unity_integration/network.md

current Unity version
![image](https://user-images.githubusercontent.com/64897247/127514931-b938c57e-aff7-4d0f-b550-98955bd6b001.png)

network.md
![image](https://user-images.githubusercontent.com/64897247/127515099-0c63977d-ad95-4a0b-be14-a9430b11363e.png)

**Comment by sdiao** [comment]
Hi @KazukiKuriyama , thanks for letting us know about the mismatch in the ROS Settings window. We will update the screenshot. Yes, there is no need to set the Unity IP in Unity Editor. Please let us know if you have further questions.

**Comment by KazukiKuriyama** [comment]
Regarding "Explicitly set the UNITY_IP" described in "2. Can ROS send messages to Unity?", Where should I clarify it?
Is this also unnecessary now?

**Comment by sdiao** [comment]
Apologies for the outdated doc. We will update the doc. You should not need to set the UNITY_IP. When you start your Unity scene, it should open the connection between Unity and ROS, and ROS can send messages to Unity. I would recommend check out the Subscriber tutorial.

**Comment by sdiao** [comment]
I have pushed the document update to dev branch. Close the issue now. Please feel free to reach out if you have any question in the future.
