### ISSUE TITLE
ROS 2 Action Support

### ISSUE THREAD

**Issue by connormbrooks** [Unity-Technologies/Unity-Robotics-Hub#290]
Are you planning to/currently supporting actions in ROS 2 now that the package supports integration with ROS 2?

I saw this issue: #202 discussing implementing an action client as shown in the tutorial; however, that action client is based on ROS 1's actions which are topic-based and fundamentally different from ROS 2's service-based actions.

Thanks!

**Comment by at669** [comment]
Hi, thanks for reaching out! At this time, we don't have support for ROS 2 actions, but we have an internal ticket to investigate this feature for future releases.

[Ticket#: AIRO-1126]

**Comment by connormbrooks** [comment]
Great, thanks for the info!
