### ISSUE TITLE
Outdated ROS Settings Instruction and Window in Pick-and-Place Tutorial

### ISSUE THREAD

**Issue by A-Ivan** [Unity-Technologies/Unity-Robotics-Hub#292]
**Describe the bug**
Hi Unity Robotics Team.

I just wanted to let you know that there is an outdated ROS Settings Instructions and Window in the Pick-and-Place Tutorial - [Part 2](https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/main/tutorials/pick_and_place/2_ros_tcp.md#the-unity-side)

The Unity Side - Item 9 - The ROS settings setup instructions and window image are out of date (still shows/mentions Override Unity IP Address)

"If you are running ROS services in a Docker container, fill ROS IP Address with the loopback IP address 127.0.0.1 and the Override Unity IP Address as your local machine's IP address. "

![image](https://user-images.githubusercontent.com/17125077/129401050-bc8f161b-95e2-4f40-a099-b262d53506bf.png)

**Comment by at669** [comment]
Hey @A-Ivan, thanks for letting us know! We'll make sure this instruction gets updated.

[Ticket#: AIRO-1133]

**Comment by at669** [comment]
@A-Ivan, the fix has been merged to the `dev` branch and will make its way to `main` in the next release. I'll close out this issue now--thanks for bringing it to our attention!
