### ISSUE TITLE
ROS TCP handshake fails in Part 2 and No menu tab names Override Unity IP Address

### ISSUE THREAD

**Issue by JounMinPark** [Unity-Technologies/Unity-Robotics-Hub#295]
I have similar error like the link below, It get connects to the ROS but dosen't show the hearing message on the ROS
![image](https://user-images.githubusercontent.com/62640611/130096716-716acc9a-293f-4617-b7f1-427e3d92f0fd.png)

https://github.com/Unity-Technologies/Unity-Robotics-Hub/issues/170
Title: ROS TCP handshake fails in Part 2, even after double checking the ROS_IP settings #170

but the difference is that I could not change the "Override Unity IP Address" since there in no tab in my ROS settings

![image](https://user-images.githubusercontent.com/62640611/130096212-877961c4-bc0b-4af6-a72c-d50d7b0ceda0.png)

I am currently using Window10/Unity 2020.3.11f1 / ROS on Docker

For more detail info.

![image](https://user-images.githubusercontent.com/62640611/130163776-75b9b347-0df5-4fad-8f11-e5404a1b6d35.png)

It seems like it is connected to the ROS but when cliking publish button, no messages are shown in the ROS

**Comment by DiosVan** [comment]
HI, @JounMinPark Override Unity IP Address has been removed in the latest version of RosSettings, 
your situation is very similar to mine.
Although I still have some doubts about this topic, but maybe you can refer to my solution [this](https://github.com/Unity-Technologies/Unity-Robotics-Hub/issues/273#issuecomment-899948274), remember to rebuild docker image after modification.

**Comment by JounMinPark** [comment]
Thank you for giving me help,

after rebuilding the docker image and modifying the script it worked  successfully!!!

![image](https://user-images.githubusercontent.com/62640611/130176308-0fcb7a63-633d-4b6d-b8b3-b76d617f9b99.png)

![image](https://user-images.githubusercontent.com/62640611/130176542-d3653a6f-7821-4d65-90ae-8a912e4d879f.png)

**Comment by DiosVan** [comment]
Good job, we also look forward to the official response to this issue.:)

**Comment by vidurvij-Unity** [comment]
I am glad this solution worked out for you. I am investigating wether this is a potential bug that needs to be fixed. I will get back to you with a proper solution.

**Comment by peifeng-unity** [comment]
You are right that this is related to issue #273. [A fix](https://github.com/Unity-Technologies/Unity-Robotics-Hub/pull/308) has been merged to the `dev` branch. Please let us know if it would work for you on the most recent dev branch.
