### ISSUE TITLE
Basic Error found while running ROS node to subscribe to topic /pos_rot published by Unity (Following Unity Publisher tutorial)

### ISSUE THREAD

**Issue by Akashleena** [Unity-Technologies/Unity-Robotics-Hub#296]
**Describe the bug**
I followed the [Publisher tutorial](https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/main/tutorials/ros_unity_integration/publisher.md)) to publish the pose of the robot on/pos_rot topic. On the ROS side I have written a C++ node which can read thode messages and display on the console. Later I plan to publish those messages to Gazebo.

I am getting a couple of errors in the src/unity_subscribe.cpp as also the CMakelists.txt

**unity_subscribe.cpp** 
![unitysubscribecpp(1)](https://user-images.githubusercontent.com/37972955/130214103-7b229fb0-c562-4c13-b61a-9e408aaf5972.jpg)
![unitysubscribecpp(2)](https://user-images.githubusercontent.com/37972955/130214140-bdc78f21-6943-42b3-aa9e-cc87e7ea773a.jpg)

**CMakeLists.txt**
![CMakelists](https://user-images.githubusercontent.com/37972955/130214166-f968e29f-6503-4353-abdd-c8c513fa53e3.jpg)
![package xml](https://user-images.githubusercontent.com/37972955/130214189-fb1a4359-db25-41ab-b9ac-477187b6fcd2.jpg)

**Errors I am getting:**
![error in cmakelists](https://user-images.githubusercontent.com/37972955/130214458-ef2b3db8-fca7-49b8-bacb-596a50de7722.png)

To remove the above error, I commented the line in CMakeLists.txt to remove the error.. (But since in the cpp code I am trying to subscribe to the topics sent by Unity and reading those messages and dispalying it on the console, I think I need Line 30 add_dependencies(unity_subscribe robo_simulation_generate_messages_cpp) in the CMakeLists.txt

**Error 2: After removing Line 30 add_dependencies line from CMakeLists.txt**

![includeunitymessage error](https://user-images.githubusercontent.com/37972955/130215214-3507a004-d703-4ff8-abb0-2847d8e034bd.jpg)

I have checked the syntax to include a custom message header file in  [ROS WIKI](http://wiki.ros.org/ROS/Tutorials/DefiningCustomMessages)

and I feel my syntax is correct. I have also placed the unity_robotics_demo_msgs  package inside the src folder of my workspace.
My directory structure is as follows
To Reproduce the errors and check my directory structure

just clone this [package](https://github.com/Akashleena/unity_gazebo_ros) and place it in the src/ folder of your catkin workspace 
(~/catkin_ws/src/unity_gazebo_ros) and do a catkin_make

**Comment by vidurvij-Unity** [comment]
I checked out the project, it seems that your folder hierarchy for ROS packages is incorrect. All the packages should be in src level of your working directory but it seems you have moved "unity_robotics_demo_msgs" inside your Robo_simulation folder. I moved it to unity_gazebo_ros/src folder and completed the build. 
I hope this helped and feel free to ask any other questions you have. !

**Comment by Akashleena** [comment]
Thanks that works.
I headed on and copied and pasted the ROS_TCP_ENDPOINT package in my catkin_ws
A catkin_make builds the package successfully.

However on doing $rosrun ros_tcp_endpoint default_server_endpoint.py 

I get this error:
Traceback (most recent call last):
  File "/home/akashleena/gazebo_unity_ros_ws/src/ROS-TCP-Endpoint/src/ros_tcp_endpoint/default_server_endpoint.py", line 3, in <module>
    import rospy
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/__init__.py", line 47, in <module>
    from std_msgs.msg import Header
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/__init__.py", line 1, in <module>
    from ._Bool import *
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/_Bool.py", line 6, in <module>
    import genpy
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/__init__.py", line 34, in <module>
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/message.py", line 48, in <module>
    import yaml
ImportError: No module named yaml

**Comment by Akashleena** [comment]
Is there a way to align Unity and Gazebo co-ordinate system?

**Comment by vidurvij-Unity** [comment]
ROS TCP Connector provides APIs for converting coordinate systems.
https://github.com/Unity-Technologies/ROS-TCP-Connector/blob/main/ROSGeometry.md
If you have any further questions, feel free to open a new issue.
Vidur

**Comment by Akashleena** [comment]
Yup, thanks a tonne, the original issue was resolved
