### ISSUE TITLE
URDF Tutorials Appendix Links not working

### ISSUE THREAD

**Issue by A-Ivan** [Unity-Technologies/Unity-Robotics-Hub#298]
The table of contents links on the "URDF Tutorials Appendix" [document ](https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/main/tutorials/urdf_importer/urdf_appendix.md) are not working.

For instance:

File Hierarchy
GameObject Hierarchy
URDF Comparator
Articulation Body axis definition
Etc.

The problem is that there is an extra "#" symbol in their links, making these links unclickable, I believe it should only contain one of these symbols, not two.

An example is File Hierarchy currently has the following link "https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/main/tutorials/urdf_importer/urdf_appendix.md##File-Hierarchy"

I believe it should be "https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/main/tutorials/urdf_importer/urdf_appendix.md#File-Hierarchy".

This change should fix all of these links.

**Comment by vidurvij-Unity** [comment]
Thank you for pointing this out to us. I have created a pull requested to make the necessary changes.

**Comment by A-Ivan** [comment]
You're welcome
