### ISSUE TITLE
 lk problem in this dome

### ISSUE THREAD

**Issue by wh1998ya** [Unity-Technologies/Unity-Robotics-Hub#340]
I want to move the end of the robotic arm to any position in this dome. How do I do this?

**Comment by at669** [comment]
Hi @wh1998ya--I have responded to this on your [Robotics Forum post](https://forum.unity.com/threads/how-to-use-the-lk-solver-of-ros-in-the-pick-and-placeproject-dome-to-control-the-end-pose-of-niryo-o.1220052/). I will close out this issue in order to consolidate the discussion. Thanks!
