### ISSUE TITLE
TCP Socket Exception

### ISSUE THREAD

**Issue by LikithRana** [Unity-Technologies/Unity-Robotics-Hub#66]
Hello,

I am following the pick-and-place tutorial which comprises of 3 parts. I have followed every step and have encountered no problems up until the very last step of the Part 2. When I click on the 'publish' button in the game mode of Unity, I am getting the following exception:
![2020-12-02_16h22_53](https://user-images.githubusercontent.com/56895056/100892417-99925e80-34ba-11eb-8e67-8219b66de591.png)

On the ROS side, "roslaunch" command is running but it doesn't print any data :
![2020-12-02_16h24_26](https://user-images.githubusercontent.com/56895056/100892624-d0687480-34ba-11eb-8953-f8cda92f0d9c.png)

I have disabled firewall and tried too but no success. Can you please let me know if I am missing something? I apologize if this is a simple issue but I am new to this. Hence I am not sure what else can I do next to figure it out? Thank you.

Additional Information:
Unity - on Windows
ROS - on VM (Ubuntu 18.04)

**Comment by mrpropellers** [comment]
Hi Likith! This looks to be an issue with how your network adapters are set up in your virtual machine. You may need to do some troubleshooting to ensure that your guest OS can talk to your host OS and vice versa. One simple way to do this is to set up a "Host-Only" style network, but this varies based on what virtualization software you're using and you'll have to do a little searching around the internet to find a good solution for your setup.  Try and ensure that you can `ping` your host OS's IP from inside the guest, and can `ping` the guest from the host, then try this last step again. If the ping works, but the ROS communication still fails, then there may be an issue to investigate here, but my hunch is that there is just some additional configuration needed for your VM's network settings.

**Comment by LikithRana** [comment]
Hello @mrpropellers, It worked once I setup "Host-Only" network in my Virtual Machine. Thank you very much for the quick response and your help.

Just for reference, I followed the below links to setup "Host-only" network:
https://serverfault.com/questions/225155/virtualbox-how-to-set-up-networking-so-both-host-and-guest-can-access-internet
https://www.youtube.com/watch?v=73ccYLqGb_k

**Comment by mrpropellers** [comment]
Great!  That will be a useful resource for us to pass to future users that encounter similar issues.  Since it seems like your issue is resolved, I'm going to go ahead and close this ticket, thanks!

**Comment by mrpropellers** [comment]
Don't mind me, just adding some additional text to make this issue more searchable:

> SocketException: A connection attempt failed because the connected party did not respond after a period of time, or established connection failed because connected host has failed to respond
TCPConnector Exception: System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
