### ISSUE TITLE
Wrong mesh files in niryo_one.urdf

### ISSUE THREAD

**Issue by JPABotermans** [Unity-Technologies/Unity-Robotics-Hub#80]
Hi,

When looking at the niryo_one.urdf file, it seems that for the grippers the wrong clamps are attached. Is this correct?

![image](https://user-images.githubusercontent.com/45882689/102822442-5cdec680-43d9-11eb-924c-5d61f44ad9a1.png)

**Comment by vidurvij-Unity** [comment]
Hi @JPABotermans ,
Thank you for bringing this to our attention. The mesh files are identical and functionally are working correctly. We will update the naming scheme in a future pull request.
Vidur

**Comment by peifeng-unity** [comment]
Hi @JPABotermans, [the fix](https://github.com/Unity-Technologies/Unity-Robotics-Hub/commit/3e229040e55d915d0b377156243d3933b770ab16) has been merged to the `dev` branch, and it will soon be merged into `main`.

I am going to close this issue. Please feel free to reopen it if there are more questions. Thank you!

-Peifeng
