### ISSUE TITLE
Add my own robot using pick-and-place demo

### ISSUE THREAD

**Issue by slxxqs** [Unity-Technologies/Unity-Robotics-Hub#82]
Hello,I want to add my own robot (ABB IRB1200) using pick-and-place demo,how can I replace the corresponding file?

**Comment by vidurvij-Unity** [comment]
Hi @slxxqs,
This repository is an end to end demo to showcase the usage of Unity with robotics. Unfortunately, you cannot directly replace the Niryo robot file with another robot in the pick and place demo.
You can use the pipeline as a template to implement your own pick and place method.

1. To import a robot you can use the [URDF Importer ](https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/main/tutorials/urdf_importer/urdf_tutorial.md)
2. For trajectory planning we use the[ MoveIT](https://moveit.ros.org) in ROS
3. To support communication between ROS and Unity, you can follow [these](https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/main/tutorials/ros_unity_integration/README.md) tutorials.

Thank you for checking out this project. Let me know if you need more information.
Vidur
