### ISSUE TITLE
URDF issue

### ISSUE THREAD

**Issue by ToniRV** [Unity-Technologies/Unity-Robotics-Hub#89]
The end effector breaks (as shown in the video below) for the pick-and-place tutorial.

**Comment by ToniRV** [comment]
https://user-images.githubusercontent.com/9856163/103941392-c3afef80-50fc-11eb-9501-bc972eb36601.mp4

**Comment by LaurieCheers-unity** [comment]
Thanks. This issue has been fixed in our latest version of the URDF file, the changes should end up in main branch soon.
